### ISSUE TITLE
Error: Cannot find module 'react-redux/lib/utils/storeShape'

### ISSUE THREAD

**Issue by jordansexton** [reactjs/react-redux#632]
5.0.3 contains a breaking change introduced in 4d302257e3b361731f44b1f546e547ed578c8eec if you're using the shapes provided.

**Comment by timdorr** [comment]
Directly importing a module is not a supported behavior. It's considered a private API.

**Comment by LKay** [comment]
Well, it is a breaking change indeed. When doing such thing it is wise to follow semver and I think it should be release as `5.1.0` instead of `5.0.3`

**Comment by markerikson** [comment]
Well, if it's a _breaking_ change, semver would dictate this should be 6.0.0.

The argument here is that changes to non-public APIs don't qualify as "breaking".

**Comment by jordansexton** [comment]
I think reasonable engineers can debate what is or isn't considered a private API, but there's little harm in updating the minor version rather than the patch, and it provides some indication of the relative risk.

**Comment by gaearon** [comment]
If you look at the README, you won't see any mention of this file. This means it is a private API, and can change or be removed in any patch version. Please don't use undocumented private APIs.

**Comment by jdmswong** [comment]
I'm having this error after a fresh npm install, how do I fix it?
